name: Juice Shop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Run on GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build frontend
      - name: Build frontend
        run: npm run build:frontend

      # Step 5: Build server
      - name: Build server
        run: npm run build:server

      # Step 6: Run tests
      - name: Run tests
        run: npm test

      # --------------------------
      # Step 7: SonarQube Scan
      # --------------------------
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=juice-shop-demo \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://10.158.124.198:9000 \
            -Dsonar.login=$SONAR_TOKEN
