name: Juice Shop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Cache frontend node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          frontend-node-modules-

    - name: Install frontend dependencies
      run: npm install --legacy-peer-deps
      working-directory: frontend
      shell: powershell

    - name: Build frontend
      run: |
        set NODE_OPTIONS=--max_old_space_size=4096
        npx ng build --configuration production --source-map=false
      working-directory: frontend
      shell: powershell

  server:
    runs-on:
      - self-hosted
      - Windows
      - X64
    needs: frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Install server dependencies
      run: npm install --legacy-peer-deps
      shell: powershell

    - name: Build server
      run: npm run --silent build:server
      shell: powershell

    - name: SonarQube Scan
      run: |
        set SONAR_HOST_URL=http://127.0.0.1:9000
        set SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        sonar-scanner
      shell: powershell
