name: Juice Shop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js 22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      # 3️⃣ Cache frontend dependencies
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: frontend-node-modules-

      # 4️⃣ Cache server dependencies
      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: server-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: server-node-modules-

      # 5️⃣ Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        working-directory: frontend
        shell: powershell

      # 6️⃣ Build frontend incrementally with 4GB memory
      - name: Build frontend
        run: |
          set NODE_OPTIONS=--max_old_space_size=4096
          npx ng build --configuration production --source-map=false --incremental
        working-directory: frontend
        shell: powershell

      # 7️⃣ Install server dependencies
      - name: Install server dependencies
        run: npm install --legacy-peer-deps
        shell: powershell

      # 8️⃣ Build server
      - name: Build server
        run: npm run --silent build:server
        shell: powershell

      # 9️⃣ SonarQube scan
      - name: SonarQube Scan
        run: |
          set SONAR_HOST_URL=http://185.134.88.1:9000
          set SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          sonar-scanner
        shell: powershell
