name: Juice Shop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Run on your self-hosted Windows VM
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build frontend
      - name: Build frontend
        run: npm run build:frontend

      # Step 5: Build server
      - name: Build server
        run: npm run build:server

      # Step 6: Run tests
      - name: Run tests
        run: npm test

      # --------------------------
      # SonarQube Integration
      # --------------------------

      # Step 7: Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
          tar -xf sonar-scanner.zip -C $env:USERPROFILE
          echo "$env:USERPROFILE\sonar-scanner-5.0.1.3006-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Step 8: Run SonarQube scan
      - name: SonarQube Scan
        run: |
          sonar-scanner `
            -Dsonar.projectKey=juice-shop-demo `
            -Dsonar.sources=. `
            -Dsonar.host.url=http://10.158.124.198:9000 `
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
