name: Juice Shop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js 22
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      shell: powershell

    # 4️⃣ Build frontend with 4GB memory
    - name: Build frontend
      run: |
        cd frontend
        set NODE_OPTIONS=--max_old_space_size=4096
        npx ng build --configuration production --source-map=false
        cd ..
      shell: powershell

    # 5️⃣ Build server
    - name: Build server
      run: npm run --silent build:server
      shell: powershell

    # 6️⃣ Run tests
    - name: Run tests
      run: npm test
      shell: powershell

    # 7️⃣ SonarQube scan
    - name: SonarQube Scan
      run: |
        set SONAR_HOST_URL=http://185.134.88.1:9000
        set SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        sonar-scanner
      shell: powershell
