name: Juice Shop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    # 3️⃣ Cache frontend dependencies
    - name: Cache frontend node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: node-modules-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          node-modules-

    # 4️⃣ Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install --legacy-peer-deps
      shell: powershell

    # 5️⃣ Build frontend with 4GB memory
    - name: Build frontend
      run: |
        set NODE_OPTIONS=--max_old_space_size=4096
        cd frontend
        npx ng build --configuration production --source-map=false
      shell: powershell

    # 6️⃣ Build server
    - name: Build server
      run: |
        cd ..
        npm run --silent build:server
      shell: powershell

    # 7️⃣ Run tests
    - name: Run tests
      run: |
        npm test
      shell: powershell

    # 8️⃣ SonarQube scan
    - name: SonarQube Scan
      run: |
        set SONAR_HOST_URL=http://185.134.88.1:9000
        set SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        sonar-scanner
      shell: powershell
