name: Juice Shop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js 22
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        npm ci
      shell: powershell

    # 4️⃣ Build frontend with increased memory
    - name: Build frontend
      run: |
        set NODE_OPTIONS=--max_old_space_size=4096
        cd frontend
        npx ng build --configuration production --source-map=false
      shell: powershell

    # 5️⃣ Build server
    - name: Build server
      run: |
        cd ..
        npm run --silent build:server
      shell: powershell

    # 6️⃣ Run tests
    - name: Run tests
      run: |
        npm test
      shell: powershell

    # 7️⃣ SonarQube scan (local VM example)
    - name: SonarQube Scan
      run: |
        set SONAR_HOST_URL=http://185.134.88.1:9000
        set SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        sonar-scanner
      shell: powershell
