name: Juice Shop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Use your self-hosted runner on the VM
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build:frontend

    - name: Build server
      run: npm run build:server

    - name: Run tests
      run: npm test

    - name: SonarQube Scan
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner \
          -Dsonar.projectKey=juice-shop-demo \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=.
