name: Juice Shop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    runs-on:
      - self-hosted
      - Windows
      - X64
    outputs:
      node-path: ${{ steps.node.outputs.node-path }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      id: node
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      shell: powershell

  build-frontend:
    needs: setup
    runs-on:
      - self-hosted
      - Windows
      - X64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Build frontend
      run: |
        set NODE_OPTIONS=--max_old_space_size=4096
        cd frontend
        npx ng build --configuration production --source-map=false
      shell: powershell

  build-server:
    needs: setup
    runs-on:
      - self-hosted
      - Windows
      - X64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Build server
      run: npm run --silent build:server
      shell: powershell

  sonar-scan:
    needs: [build-frontend, build-server]
    runs-on:
      - self-hosted
      - Windows
      - X64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarQube Scan
      run: |
        set SONAR_HOST_URL=http://185.134.88.1:9000
        set SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        sonar-scanner
      shell: powershell
